name: blast_blastn
description: Queries a BLAST DNA database
keywords:
    - fasta
    - blast
    - blastn
    - DNA sequence
tools:
    - blast:
        description: |
            BLAST finds regions of similarity between biological sequences.
        homepage: https://blast.ncbi.nlm.nih.gov/Blast.cgi
        documentation: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=Blastdocs
        doi: 10.1016/S0022-2836(05)80360-2
params:
    - outdir:
        type: string
        description: |
            The pipeline's output directory. By default, the module will
            output files into `$params.outdir/<SOFTWARE>`
    - publish_dir_mode:
        type: string
        description: |
            Value for the Nextflow `publishDir` mode parameter.
            Available: symlink, rellink, link, copy, copyNoFollow, move.
    - enable_conda:
        type: boolean
        description: |
            Run the module with Conda using the software specified
            via the `conda` directive
    - singularity_pull_docker_container:
        type: boolean
        description: |
            Instead of directly downloading Singularity images for use with Singularity,
            force the workflow to pull and convert Docker containers instead.
input:
    - meta:
        type: map
        description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: Input fasta file containing queries sequences
        pattern: "*.{fa,fasta}"
    - db:
        type: directory
        description: Directory containing blast database
        pattern: "*"
output:
    - txt:
        type: file
        description: File containing blastn hits
        pattern: "*.{blastn.txt}"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@joseespinosa"
    - "@drpatelh"
