name: untar
description: Extract files.
keywords:
    - untar
    - uncompress
tools:
    - untar:
        description: |
            Extract tar.gz files.
        documentation: https://www.gnu.org/software/tar/manual/
params:
    - outdir:
        type: string
        description: |
            The pipeline's output directory. By default, the module will
            output files into `$params.outdir/<SOFTWARE>`
    - publish_dir_mode:
        type: string
        description: |
            Value for the Nextflow `publishDir` mode parameter.
            Available: symlink, rellink, link, copy, copyNoFollow, move.
    - enable_conda:
        type: boolean
        description: |
            Run the module with Conda using the software specified
            via the `conda` directive
    - singularity_pull_docker_container:
        type: boolean
        description: |
            Instead of directly downloading Singularity images for use with Singularity,
            force the workflow to pull and convert Docker containers instead.
input:
    - archive:
        type: file
        description: File to be untar
        pattern: "*.{tar}.{gz}"
output:
    - untar:
        type: file
        description:
        pattern: "*.*"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@joseespinosa"
    - "@drpatelh"
