name: bedtools_getfasta
description: extract sequences in a FASTA file based on intervals defined in a feature file.
keywords:
    - bed
    - fasta
    - getfasta
tools:
    - bedtools:
        description: |
            A set of tools for genomic analysis tasks, specifically enabling genome arithmetic (merge, count, complement) on various file types.
        documentation: https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html
params:
    - outdir:
          type: string
          description: |
              The pipeline's output directory. By default, the module will
              output files into `$params.outdir/<SOFTWARE>`
    - publish_dir_mode:
          type: string
          description: |
              Value for the Nextflow `publishDir` mode parameter.
              Available: symlink, rellink, link, copy, copyNoFollow, move.
    - enable_conda:
          type: boolean
          description: |
              Run the module with Conda using the software specified
              via the `conda` directive
    - singularity_pull_docker_container:
          type: boolean
          description: |
              Instead of directly downloading Singularity images for use with Singularity,
              force the workflow to pull and convert Docker containers instead.
input:
    - bed:
        type: file
        description: Bed feature file
        pattern: "*.{bed}"
    - fasta:
        type: file
        description: Input fasta file
        pattern: "*.{fa,fasta}"

output:
    - fasta:
        type: file
        description: Output fasta file with extracted sequences
        pattern: "*.{fa}"
    - version:
        type: file
        description: File containing software version
        pattern: "*.{version.txt}"
authors:
    - "@joseespinosa"
    - "@drpatelh"
