name: nf-core CI
# This workflow is triggered on pushes and PRs to the repository.
# It runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on: [push, pull_request]

jobs:
  test:
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['19.10.0', '']
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Pull docker image
        run: |
          docker pull nfcore/viralrecon:dev
          docker tag nfcore/viralrecon:dev nfcore/viralrecon:dev
      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker

  parameters:
    env:
      NXF_VER: '19.10.0'
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parameters: [--skip_trimming, --skip_assembly, --skip_variants]
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Pull docker image
        run: |
          docker pull nfcore/viralrecon:dev
          docker tag nfcore/viralrecon:dev nfcore/viralrecon:dev
      - name: Run pipeline with test amplicon data with various options
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker ${{ matrix.parameters }}

  test_sispa:
    env:
      NXF_VER: '19.10.0'
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parameters: [--skip_trimming, --skip_assembly, --skip_variants]
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Pull docker image
        run: |
          docker pull nfcore/viralrecon:dev
          docker tag nfcore/viralrecon:dev nfcore/viralrecon:dev
      - name: Run pipeline with test SISPA data with various options
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_sispa,docker ${{ matrix.parameters }}

  test_full_sispa:
    env:
      NXF_VER: '19.10.0'
      NXF_ANSI_LOG: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parameters: [--skip_sra, --skip_trimming, --skip_assembly, --skip_variants]
    steps:
      - uses: actions/checkout@v2
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Pull docker image
        run: |
          docker pull nfcore/viralrecon:dev
          docker tag nfcore/viralrecon:dev nfcore/viralrecon:dev
      - name: Run pipeline with full SISPA data via SRA ids with various options
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_full_sispa,docker ${{ matrix.parameters }}
